---
# tasks file for roles/vector
- name: VECTOR | Get distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "/tmp/vector_{{ vector_version }}-1_amd64.deb"
    mode: "0644"

- name: VECTOR | Install packages
  become: true
  ansible.builtin.apt:
    deb: "/tmp/vector_{{ vector_version }}-1_amd64.deb"

- name: VECTOR | Configurate
  block:
    - name: VECTOR | Deploy config
      become: true
      ansible.builtin.template:
        src: vector.j2
        dest: /etc/vector/vector.yaml
        mode: "0644"
    - name: VECTOR | Create systemd service
      become: true
      ansible.builtin.template:
        src: vector.service.j2
        dest: /lib/systemd/system/vector.service
        mode: "0644"
      notify: Start Vector
